// ADD
export const ADD_EMPLOYER_SUCCESS = 'ADD_EMPLOYER_SUCCESS';
export const ADD_EMPLOYER_REQUEST = 'ADD_EMPLOYER_REQUEST';
export const ADD_EMPLOYER_FAILURE = 'ADD_EMPLOYER_FAILURE';

// DELETE
export const DELETE_EMPLOYER_SUCCESS = 'DELETE_EMPLOYER_SUCCESS';
export const DELETE_EMPLOYER_REQUEST = 'DELETE_EMPLOYER_REQUEST';

// EDIT
export const EDIT_EMPLOYER_SUCCESS = 'EDIT_EMPLOYER_SUCCESS';
export const EDIT_EMPLOYER_REQUEST = 'EDIT_EMPLOYER_REQUEST';
